---
- hosts: all
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  gather_facts: true

- name: Assemble Consul cluster
  hosts: "{{ host }}"
  any_errors_fatal: true
  become: true
  become_user: root
  roles:
    - ansible-consul
